[package]
name = "dotfiles"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.80" }
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = { version = "0.9.32" }
termcolor = { version = "1.4.1" }
