[package]
name = "dotfiles"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75" }
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = { version = "0.9.27" }
termcolor = { version = "1.4.0" }
