[package]
name = "dotfiles"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.91" }
serde = { version = "1.0.213", features = ["derive"] }
serde_yaml = { version = "0.9.34" }
termcolor = { version = "1.4.1" }
