[package]
name = "dotfiles"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.72" }
serde = { version = "1.0.176", features = ["derive"] }
serde_yaml = { version = "0.9.25" }
termcolor = { version = "1.2.0" }
