[package]
name = "dotfiles"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.76" }
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = { version = "0.9.28" }
termcolor = { version = "1.4.0" }
