homebrew:
  formulae:
    - bash-language-server
    - bat
    - coreutils
    - curl
    - deno
    - esbuild
    - eza
    - fd
    - fzf
    - gh
    - git
    - go
    - gopls
    - helix
    - htop
    - jq
    - llvm
    - lua-language-server
    - marksman
    - ncurses
    - neofetch
    - neovim
    - node
    - parallel
    - protobuf
    - ripgrep
    - ruff
    - ruff-lsp
    - rust-analyzer
    - shellcheck
    - sqlite
    - starship
    - staticcheck
    - tmux
    - typescript-language-server
    - vips
    - wget
    - wrk
    - yaml-language-server
    - zig
    - zls
    - zsh
    - zsh-completions
  casks:
    - alacritty
    - font-monaspace-nerd-font
    - font-sauce-code-pro-nerd-font

npm:
  packages:
    - svelte-language-server
    - vscode-langservers-extracted

rules:
  # alacritty
  - src: "data/alacritty/alacritty.toml"
    dst: "$HOME/.config/alacritty/alacritty.toml"

  # helix
  - src: "data/helix/config.toml"
    dst: "$HOME/.config/helix/config.toml"
  - src: "data/helix/languages.toml"
    dst: "$HOME/.config/helix/languages.toml"

  # neovim
  - src: "data/nvim/init.lua"
    dst: "$HOME/.config/nvim/init.lua"

  # psql
  - src: "data/psql/.psqlrc"
    dst: "$HOME/.psqlrc"

  # starship
  - src: "data/starship/starship.toml"
    dst: "$HOME/.config/starship.toml"

  # tmux
  - src: "data/tmux/.tmux.conf"
    dst: "$HOME/.tmux.conf"

  # vim
  - src: "data/vim/.vimrc"
    dst: "$HOME/.vimrc"

  # vscode
  - src: "data/vscode/settings.json"
    dst:
      linux: "$HOME/.config/Code/User/settings.json"
      macos: "$HOME/Library/Application Support/Code/User/settings.json"

  # zed
  - src: "data/zed/settings.json"
    dst: "$HOME/.config/zed/settings.json"
  - src: "data/zed/keymap.json"
    dst: "$HOME/.config/zed/keymap.json"

  # zsh
  - src: "data/zsh/.zshrc"
    dst: "$HOME/.zshrc"
